### ISSUE TITLE
In review list of images takes 1/3 of screen wasting space

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#104]
In review mode list of images takes 1/3 of screen giving very little (if any) useful information leaving for image itself barely 1/2 of screen.
<img width="1280" alt="screenshot" src="https://user-images.githubusercontent.com/1630974/44207506-d0170480-a15d-11e8-87a0-a0bddadb6bd9.png">

**Comment by manuaero** [comment]
Agreed - we will be revising this screen soon.

**Comment by valeriyvan** [comment]
👍🏾

**Comment by manuaero** [comment]
We just optimized this screen and made the rows smaller. 

<img width="694" alt="screen shot 2018-09-24 at 7 10 59 pm" src="https://user-images.githubusercontent.com/3059998/45988813-9921f180-c02d-11e8-8731-9cc7a6c6704a.png">

**Comment by valeriyvan** [comment]
still 1/3 of width of images list is wasted.
