### ISSUE TITLE
Labeled data url gives Invalid HTTP method/URL pair

### ISSUE THREAD

**Issue by ihabZhaika** [Labelbox/Labelbox#105]
Hey,

I have labeled the data, then i hit export,when i open the output json the masks urls are on amazon and they work as they should, but when i click on "Labeled Data" url, it's hosted on fire base and i get the following error

`{
  "error": {
    "code": 400,
    "message": "Invalid HTTP method/URL pair."
  }
}`

i tried to export few times, but same issue, tried to export in csv it worked, so is there any knows issue with the json export

**Comment by danielrasmuson** [comment]
Hmm. The "Labeled Data" column should be the same as the asset you  saw while labeling. Are you able to share more information? Such as the url that isn't working.

**Comment by ihabZhaika** [comment]
Hey,
i will close this issue, the links worked after few hours, which is weird
