### ISSUE TITLE
TypeError: string indices must be integers (Label2Pascal)

### ISSUE THREAD

**Issue by GottliebFreudenreich** [Labelbox/Labelbox#107]
When exporting the label as XY format the label2pascal script throws an error: 

`Labelbox/scripts/labelbox2pascal/__init__.py", line 116, in <listcomp>
    for x, y in [(p['x'], p['y']) for p in polygon]:
TypeError: string indices must be integers
`

As mentioned in #106 label format WKT is also not exported correctly.

**Comment by feynmanliang** [comment]
Thanks for the report, and you're right this is a problem! To keep the discussion in the same place, I'm going to close this issue and continue the thread in #106

**Comment by GottliebFreudenreich** [comment]
Thank you! Hopefully you can fix this. We would love to stick to labelbox
