### ISSUE TITLE
[ENG-405] Error while trying to run labelbox2coco on image segmentation v3 label

### ISSUE THREAD

**Issue by hkuyam008** [Labelbox/Labelbox#109]
Traceback (most recent call last):
  File "C:/PyCharmProjects/Labelbox/scripts/labelbox2coco.py", line 11, in <module>
    lb2co.from_json(labeled_data=labeled_data, coco_output=coco_output)
  File "C:\PyCharmProjects\Labelbox\scripts\labelbox2coco\__init__.py", line 64, in from_json
    for cat in data['Label'].keys():
AttributeError: 'list' object has no attribute 'keys'

Process finished with exit code 1

looks like the code is expecting data in a specific format and labelbox is exporting data  in a different format.

FYI... I used options JSON & WKT while exporting so that shouldn't be an issue

**Comment by feynmanliang** [comment]
Confirmed. Would you mind adding a `print(data)` before L64? If data sensitivity is an issue, do you mind providing the format of `data` and confirming that WKT export suceeded?

**Comment by feynmanliang** [comment]
I've added https://github.com/Labelbox/Labelbox/blob/master/scripts/test-fixtures/v2_wkt.json and https://github.com/Labelbox/Labelbox/blob/master/scripts/test-fixtures/v3_wkt.json for you to test against. Hope that's helpful!

**Comment by hkuyam008** [comment]
sure will verify my fix against the test cases and confirm.

**Comment by feynmanliang** [comment]
Whoops sorry I realized the test cases I provided have an error; I've just updated them. Apologies for the inconvenience!

**Comment by hkuyam008** [comment]
I noticed the "Label" element in the test json https://github.com/Labelbox/Labelbox/blob/master/scripts/test-fixtures/v3_wkt.json you added is a dict

While the "Label" element in the Json(wkt) generated by Labelbox.com  "Export" functionality is a "list (of dicts)". The code I have handles it as a list (of dicts)

The Labelbox generated json is attached for reference - I have not edited / modified it in any way
[labelbox_wireframes.zip](https://github.com/Labelbox/Labelbox/files/2341358/labelbox_wireframes.zip)

Signing off for the day....I will check back in tomorrow and see if I can help

**Comment by feynmanliang** [comment]
You're right; thanks for pointing that out! I noticed a bug in our WKT implementation shortly after uploading the test data and have pushed a fix to how we generate WKT exports on the platform.

The desired behavior is that `Label` is a `dict` with keys representing class names and values representing the polygons.

For V3, the values should look like `List<Dict<"geometry", "WKT Polygon String">>` where each list element represents a polygon and should be converted into a separate COCO annotation.
For V2, the values should be a `string` representing a WKT MultiPolygon. In this case, each of the polygons in the MultiPolygon should get its own COCO annotation.

**Comment by feynmanliang** [comment]
If it's helpful, I just submitted a similar fix for the Pascal script https://github.com/Labelbox/Labelbox/pull/110/files#diff-5c2a092cdcec78e9a0ecf327c262016eR102

You should be able to do something similar for the COCO script. Don't worry about XY labels for COCO for now.

**Comment by hkuyam008** [comment]
The script you provided for pascal voc was of great help....I literally copy pasted the code snippet in the coco script
I have tested the code fix on both my data and the 2 test cases for V2 & V3 that you added. PFA the converted dataset files.
I have also added the modified labelbox2coco py file. You may check-in yourself or let  me know if I should check-in via a pull request

[test-fixtures.zip](https://github.com/Labelbox/Labelbox/files/2342300/test-fixtures.zip)
[__init__.zip](https://github.com/Labelbox/Labelbox/files/2342301/__init__.zip)

**Comment by feynmanliang** [comment]
This is great, thank you so much! Please submit a pull request with "Resolves #109" in the description and I'll review it

**Comment by feynmanliang** [comment]
Hey @hkuyam008 I've created https://github.com/Labelbox/Labelbox/pull/115 to get your work in and will wrap it up. I've based it off of your fork so your commit author information is retained. Once this merges, you'll be a contributor ;)

Thanks for your help!

**Comment by hkuyam008** [comment]
Thanks for your help in wrapping this up! Appreciate it.
I was a little hard pressed for time for the past couple of days
