### ISSUE TITLE
Ability to skip a label

### ISSUE THREAD

**Issue by casainfinita** [Labelbox/Labelbox#11]
There are times when a data point does not have any label. I'd like to be able to skip it or add a null label

**Comment by zacharymostowsky** [comment]
Has there been an update on this?

**Comment by zacharymostowsky** [comment]
I have went ahead and set disabled=false for the submit button in the toolbar.tsx file which allows you to submit without providing any labels. However, the submit function is set to void in toolbar.tsx. So what happens, when I run my local code, it finds my dataset I created when I log in through GitHub but it does not add the labeled row. The next time I run it starts at the first image always. Maybe I should open this as new issue.

Thanks,
Zach

**Comment by danielrasmuson** [comment]
Do you see the preview header? No labels are saved when your in preview
mode.

**Comment by zacharymostowsky** [comment]
@danielrasmuson Thank you. Exactly my problem. Great and simple application. Thanks again.

**Comment by danielrasmuson** [comment]
Wanted to announce that we also added this feature to the image classification and image segmentation templates.

<img width="1440" alt="screen shot 2018-02-05 at 10 09 14 pm" src="https://user-images.githubusercontent.com/4013767/35844258-6ccb5b70-0ac1-11e8-9c41-61865735ec31.png">

You can consume this new method in custom templates through 

```javascript
Labelbox.skip().then(() => console.log('Skip Success!'));
```

Currently, once an item is skip no other labelers will see that asset (custom formulas coming soon). Additionally, skipped assets don't show up in exports.

Feedback welcome.
