### ISSUE TITLE
can not use brush and superpixel types

### ISSUE THREAD

**Issue by ihabZhaika** [Labelbox/Labelbox#119]
Hey,
according to the documentation, the types are

tool (required)
Defines the type of tool. Can be one of: polygon, rectangle, line, point, superpixel, or brush.

so i have the following configuration:]
```
{
  "tools": [
    {
      "name": "tongue",
      "color": "green ",
      "tool": "superpixel"
    },
	    {
      "name": "tongue",
      "color": "red ",
      "tool": "brush"
    }
  ]
}
```
but they do not work, if i use the other types they tool do work, so how those two can be used ?

**Comment by feynmanliang** [comment]
Thanks for the report! The brush tool is available as an option under the superpixel too, e.g.
![image](https://user-images.githubusercontent.com/990069/45563047-fed9d680-b800-11e8-80e7-8bcaefad0233.png)

I apologize for the documentation being misleading; we'll update it to make things more clear.

**Comment by ihabZhaika** [comment]
@feynmanliang
can you post here the updated json so i can try it ?

**Comment by feynmanliang** [comment]
```
{
  "tools": [
    {
      "name": "tongue",
      "color": "green ",
      "tool": "superpixel"
    }
  ]
}
```

**Comment by ihabZhaika** [comment]
@feynmanliang
ok, as i saw the same image as you showed above, but when i select the tool, i have the hand icon and can not draw or do anything
