### ISSUE TITLE
Cross Validation of labels

### ISSUE THREAD

**Issue by caffeine-potent** [Labelbox/Labelbox#12]
Certain classifications are tough to make and may require a consensus from a group of data annotators.  A tune-able cross validation feature would be nice.   I'm not entirely convinced that this is useful to more than just my annotation projects so I'm putting this idea out here for discussion, refinement and exposure.    
  
Some examples of cross validation features:  
- setting the degree of redundancy in your labeling when initializing the project.   
- recycling classifications with which you don't agree and marking it as a contended classification when it comes into view again (possibly with the contender's name next to it)   
- choosing consensus models/criteria (IE majority, 2/3 majority, everyone) etc.

**Comment by danielrasmuson** [comment]
Thanks Otto. This post is very helpful. We are planning on adding this feature in the future.

**Comment by duncanrussell-ocado** [comment]
As an alternative to saying, sample this image 'n' times, the sampling should be based on statistical confidence of the result. When we don't have a perfect answer to compare, then we can only use statistical variance to determine the accuracy of the annotation, and the number of samples required to provide a level of confidence in the data quality. E.g. we can be more confident if an image is labelled identically by 5 people, than if 10 people label provide 10 different labels. 

This can also work by cross validation of an individual's annotation. If in a large dataset, the same individual  is shown the same data at different times and the labels disagree, the confidence in both of those labels could be lower. If that happens consistently, that individual's annotations could be excluded from the results.

**Comment by manuaero** [comment]
Hi all (cc: @caffeine-potent  @duncanrussell-ocado ),

We are excited to share a brand new feature: consensus. We call it `Auto Audit` and it is available in your account to try. 

Auto Audit lets you specify a percentage of data rows that should be labeled `n` times by distinct collaborators. We then show you an agreement score as the data is labeled. Currently we provide agreement score for only image segmentation projects.  Agreement score for image segmentation is simply an intersection over union. We will soon provide agreement score for non image segmentation tasks. Meanwhile, you can still use this feature and export the labels to perform consensus calculations yourself. 

Looking forward to hearing your feedback and ideas.

![image](https://user-images.githubusercontent.com/3059998/39204321-51be7ce0-47ac-11e8-87b2-8ed557ac9a90.png)
