### ISSUE TITLE
When entering Review mode bounding boxes on the first image doesn't appear

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#121]
When entering Review mode bounding boxes on the first image doesn't appear until switching to another image.

**Comment by valeriyvan** [comment]
No, it is not fixed.

**Comment by danielrasmuson** [comment]
@valeriyvan are still experiencing this issue? I haven't been able to reproduce it.

**Comment by valeriyvan** [comment]
No, seems to be solved.
