### ISSUE TITLE
Export labels in COCO and Pascal VOC format

### ISSUE THREAD

**Issue by raviv** [Labelbox/Labelbox#13]
For example: COCO, VOC, etc.
The current format with MULTIPOLYGON (((...))) is not very usefull
Also, the exported data should contain the original uploaded file name.

Thanks :)

**Comment by casainfinita** [comment]
Thanks for the feedback @raviv. Is there a preference among COCO, VOC or other?

**Comment by raviv** [comment]
I think that COCO and VOC are the most common ones.

**Comment by jfizzle** [comment]
a vote for VOC format

**Comment by Riegerb** [comment]
Added scripts to convert the Labelbox JSON export to COCO and Pascal VOC. After they get the bugs worked they will be added as available for export directly from Labelbox.

https://github.com/Labelbox/Labelbox/commit/2945dcca63a0260f1922d74d13521544231c61a1

**Comment by casainfinita** [comment]
Hi @jfizzle and @raviv, will much appreciate if you could test the scripts mentioned above and confirm that the converted files (COCO / Pascal) is as expected. Thanks!
