### ISSUE TITLE
In labeling interface settings compound unicode symbols are shown incorrectly

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#130]
In labeling interface settings compound unicode symbols are shown incorrectly:
<img width="1552" alt="screen shot 2018-09-28 at 18 01 33" src="https://user-images.githubusercontent.com/1630974/46223004-fb3e6780-c349-11e8-890f-107cbbc986a1.png">

But these symbols are shown correctly in labelling:
<img width="1080" alt="screen shot 2018-09-28 at 18 04 48" src="https://user-images.githubusercontent.com/1630974/46223090-3b9de580-c34a-11e8-95dc-e00a958a510b.png">

**Comment by danielrasmuson** [comment]
This does now work in the new interface configurator

<img width="575" alt="screen shot 2018-11-14 at 4 14 10 pm" src="https://user-images.githubusercontent.com/4013767/48521205-5c51ca00-e828-11e8-889f-767a11e7a9ce.png">

**Comment by valeriyvan** [comment]
What do you mean by `new interface configurator'. V3 steel shows these wrong.
