### ISSUE TITLE
Storing invalid JSON for labelling interface puts project into unusable state

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#133]
I have been editing JSON for labelling interface. After storing I can't enter project after logging in. I see empty screen. And this error in console: "SyntaxError: JSON Parse error: Unexpected comma at the end of array expression". And there's no way to fix this error.

**Comment by danielrasmuson** [comment]
Thank you for reporting this issue. We've just pushed a fix.

**Comment by valeriyvan** [comment]
Thank you!
