### ISSUE TITLE
Schrödinger's button [Start labeling]

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#136]
After adding new data set there are two buttons [Start labeling] on screen - one active and one inactive. Like [Schrödinger's cat](https://en.wikipedia.org/wiki/Schrödinger%27s_cat).

<img width="1127" alt="screen shot 2018-10-16 at 23 42 51" src="https://user-images.githubusercontent.com/1630974/47068627-14219680-d1ed-11e8-9ea2-f08091c32547.png">

**Comment by manuaero** [comment]
haha, will fix the Schrödinger's button. thanks @valeriyvan, you've been great in helping us improve LB!

**Comment by euwest** [comment]
This should be resolved; feel free to re-open if you experience this again though (or contact support through the in-app chat in the bottom right of the window for more immediate help).

**Comment by valeriyvan** [comment]
👍🏿
