### ISSUE TITLE
JSON Data Export links incorrect segmentation masks

### ISSUE THREAD

**Issue by marcoamonteiro** [Labelbox/Labelbox#138]
The JSON created from a data export is linking incorrect segmentation masks for each image. For some images the json links the correct masks, but then for the following 2-4 images the json reuses the mask from the first image. (The links are different but they point to the same mask).

For every image the "View Image" field that links to the label box interface is correct.

**Comment by euwest** [comment]
If you contact support through the in-app chat we can look into this for you; in order to diagnose the particular issue we'll need some information regarding the particular project that's better kept in private channels 😄
