### ISSUE TITLE
"undefined" in menu

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#139]
Sometime when I enter lebalebox in safari on osx I see "undefined" string instead of menu:
<img width="1392" alt="screenshot 2018-10-23 at 10 41 15" src="https://user-images.githubusercontent.com/1630974/47347839-601e8080-d6b0-11e8-94e4-5cf001c1cd27.png">

Unfortunately I can't give you steps to reproduce.

When I press [CREATE FREE ACCOUNT] button I enter site without being requested for login:

<img width="1392" alt="screenshot 2018-10-23 at 10 45 21" src="https://user-images.githubusercontent.com/1630974/47348109-01a5d200-d6b1-11e8-9a8e-a561a1381ab5.png">

I see this "undefined" state regularly at least once per day.

**Comment by danielrasmuson** [comment]
This should now be resolved.

**Comment by valeriyvan** [comment]
Have not seen this in a while. Seem to be solved.
