### ISSUE TITLE
Safari is not supported

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#143]
After several months of successfully using Labelbox suddenly I get message that Safari is not supported:

<img width="673" alt="screenshot 2018-11-14 at 20 24 03" src="https://user-images.githubusercontent.com/1630974/48507146-6cc76c00-e84b-11e8-8e2c-87f87fa4f513.png">

**Comment by danielrasmuson** [comment]
Hi @valeriyvan, we've removed the banner. We might add a not blocking banner in the future as the site does perform better on Chrome and Firefox. Thanks for the feedback.
