### ISSUE TITLE
Images stuck in queue

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#144]
All collaborators having "All done" message:
<img width="1552" alt="screen shot 2018-11-28 at 22 13 03" src="https://user-images.githubusercontent.com/1630974/49182883-bfc91500-f35b-11e8-8872-f1db0f429480.png">

But 6 images are still showing remaining in Overview:
<img width="1552" alt="screen shot 2018-11-28 at 22 12 51" src="https://user-images.githubusercontent.com/1630974/49182931-d8d1c600-f35b-11e8-9d2f-4b506448d449.png">

Queue shows 6 images, but Reserved By column is empty:
<img width="1552" alt="screen shot 2018-11-28 at 22 13 53" src="https://user-images.githubusercontent.com/1630974/49182965-f1da7700-f35b-11e8-9c92-3be57e19f0b5.png">

Seems to be a bug.

Suspect that this bug is somehow connected with #145.

Another case of same bug. 1 remaining image:
<img width="1144" alt="screenshot 2018-12-12 at 09 11 06" src="https://user-images.githubusercontent.com/1630974/49855702-4ff06b00-fdee-11e8-9619-dd395961e337.png">

And it is stuck in queue reserved by no-one:
<img width="1144" alt="screenshot 2018-12-12 at 09 10 48" src="https://user-images.githubusercontent.com/1630974/49855738-626aa480-fdee-11e8-9c20-33ce50f5e818.png">

All labellers get message "All done".

**Comment by valeriyvan** [comment]
No, the are not able to help me with this. Or are not interested.

**Comment by ryanquinn3** [comment]
@valeriyvan I've resolved your issue & sent you a message on our in-app chat. Thank you for the detailed bug report. It made it very easy to figure out the issue.
