### ISSUE TITLE
Getting Blank Preview Mode Screen

### ISSUE THREAD

**Issue by pegues** [Labelbox/Labelbox#15]
I downloaded the latest code, then navigated to templates/image-classification and ran the following as instructed:
`yarn build`

Once done, I navigated into templates/image-classification/build. I then ran:
`yarn global add serve` and `yarn serve -s build`.

I then navigate to http://localhost:5000, which then changes the URL to:

https://app.labelbox.io/development?development_url=http://localhost:5000/

I click on SECURITY CAMERA, and the URL then changes to:

http://localhost:5000/?project=cjd7f48htcy2u0112vb6rqp0v&preview=true&token=eyJ0e............pZ5-c

I then get the text 'Preview Mode' at the top of the screen, and a blank white page. From here, I looked at the error console, and get the following output.

`TypeError: this.state.customization.options is undefined
Stack trace:
value@http://localhost:5000/static/js/main.84a320c0.js:1:221702
l@http://localhost:5000/static/js/main.84a320c0.js:1:91708
beginWork@http://localhost:5000/static/js/main.84a320c0.js:1:93430
o@http://localhost:5000/static/js/main.84a320c0.js:1:105555
a@http://localhost:5000/static/js/main.84a320c0.js:1:105876
u@http://localhost:5000/static/js/main.84a320c0.js:1:106114
_@http://localhost:5000/static/js/main.84a320c0.js:1:109658
x@http://localhost:5000/static/js/main.84a320c0.js:1:109395
h@http://localhost:5000/static/js/main.84a320c0.js:1:108523
p@http://localhost:5000/static/js/main.84a320c0.js:1:107913
enqueueSetState@http://localhost:5000/static/js/main.84a320c0.js:1:82438
o.prototype.setState@http://localhost:5000/static/js/main.84a320c0.js:1:61707
value/this.customizationSubscription<@http://localhost:5000/static/js/main.84a320c0.js:1:221260
subscribe/<@https://api.labelbox.io/client/v0.1/labeling-api.js:1:33517
labeling-api.js:1:10722
TypeError: this.state.customization.options is undefined
[Learn More]
classification-options.js:30:12
TypeError: window.drift is undefined
[Learn More]
labeling-api.js:1:29876`

**Comment by danielrasmuson** [comment]
Let me know if you are still hitting this issue.
