### ISSUE TITLE
how to use it!?

### ISSUE THREAD

**Issue by ycAlex11** [Labelbox/Labelbox#150]
hi, can any one tell me how to use this ? After I went through readme, i had no idea where I am going to start !!!!!!

**Comment by danielrasmuson** [comment]
Hi @ycAlex11, Can you tell me more about your use case and the result your aiming for? Feel free to chat with us on the website as well if you're confused about anything.

**Comment by ycAlex11** [comment]
@danielrasmuson  thanks for your reply, i got it from google
