### ISSUE TITLE
go back button

### ISSUE THREAD

**Issue by Randy-Bai** [Labelbox/Labelbox#18]
Can you please add a go back button if I skipped a image or submitted a incorrectly labeled image?

**Comment by casainfinita** [comment]
Yes, @Randy-Bai. Noted.

**Comment by casainfinita** [comment]
Hi @Randy-Bai , We've added back button to image segmentation template. We will soon add this to our other templates as well. 

![image](https://user-images.githubusercontent.com/3059998/36828487-f9bd163a-1cce-11e8-9a03-a2637b953cf6.png)

You can even seek back and forward through labeled data under activity tab!
![image](https://user-images.githubusercontent.com/3059998/36828503-16e58058-1ccf-11e8-85ab-239ebe9a1dcc.png)

**Comment by Randy-Bai** [comment]
Cool!
