### ISSUE TITLE
Export multi-color masks

### ISSUE THREAD

**Issue by Randy-Bai** [Labelbox/Labelbox#19]
![0001tp_006690_l](https://user-images.githubusercontent.com/36204643/35877546-748a3174-0b2a-11e8-8b9a-e8cd77a4ac89.png)

I wish there is a link where I can review the masks and download them at one time. 

Masks with multiple colors will he helpful to multiple object detector training.

**Comment by casainfinita** [comment]
Hi @Randy-Bai, you can download the masks already at one time i.e. if you have labeled 50 data points, then when you click 'generate export` with mask option, Labelbox will generate a JSON/CSV file containing all 50 image masks in addition to label information. 

Do you find multicolor masks more useful than the binary mask per class?

**Comment by Randy-Bai** [comment]
1. Yes, it has the masks in the csv file, but it is a link. I need to put
the link in my chrome to see and download the actual mask. It is OK for me,
I can use matlab to download and rename the original images and their
masks, but maybe you can fulfill this in your end. That would be convenient
for other people who don't have much experience in coding.
2. Multicolored masks will be great.

In matlab, different colors stands for different classes. For example,
matlab will class all the pixels in the purple areas as cars.
See *https://www.mathworks.com/help/vision/examples/semantic-segmentation-using-deep-learning.html
<https://www.mathworks.com/help/vision/examples/semantic-segmentation-using-deep-learning.html>*
for details.
 [image: Inline image 1]

**Comment by feynmanliang** [comment]
This is now possible using the "superpixel" tool. For example:
![image](https://user-images.githubusercontent.com/990069/45563227-963f2980-b801-11e8-9606-a8a52158502f.png)

See https://support.labelbox.com/docs/labeling-with-superpixel for more information.

**Comment by elliestath** [comment]
but is it possible to export the annotated image image with the colored masks?
