### ISSUE TITLE
delete old project

### ISSUE THREAD

**Issue by Randy-Bai** [Labelbox/Labelbox#20]
I create some projects randomly. It seems I can't delete them.

**Comment by casainfinita** [comment]
Thanks @Randy-Bai. We are working on this and get an update out soon.

**Comment by danielrasmuson** [comment]
Hi @Randy-Bai, 

Excited to say we just added this feature.

<img width="1042" alt="screen shot 2018-02-06 at 9 24 06 pm" src="https://user-images.githubusercontent.com/4013767/35899960-2a54c77c-0b84-11e8-9ed2-a423c15f24ce.png">

Feedback welcome.
