### ISSUE TITLE
"raised" property in tool.tsx and toolbar.tsx does not exist

### ISSUE THREAD

**Issue by zacharymostowsky** [Labelbox/Labelbox#21]
Hi,

I have trouble building do to the 'raised' property not existing on type 'IntrinsicAttributes & ButtonProps & { children?: ReactNode; }

The 'rasied' property can be found on line 66 of tool.tsx and on line 75 of toolbar.tsx. If I comment these lines out it builds fine.

Thanks,
Zach

**Comment by danielrasmuson** [comment]
This sounds like a version issue to me. Are you using node v6.11.1?

One hack is you could remove the raised property on the button.
`<Button color="primary" raised={true} disabled={disableSubmit} onClick={() => onSubmit()}>Submit</Button>`

to

`<Button color="primary" disabled={disableSubmit} onClick={() => onSubmit()}>Submit</Button>`

**Comment by zacharymostowsky** [comment]
Yep, the hack works. I will look into version issue and get back to you on that.

**Comment by danielrasmuson** [comment]
Please let me know if you have any pending questions.
