### ISSUE TITLE
Searching a large number of classes in Segmentation

### ISSUE THREAD

**Issue by achinta** [Labelbox/Labelbox#23]
If we have a very large number of classes (say hundreds or thousands), we cannot filter the classes using search during labelling.

**Comment by casainfinita** [comment]
Thanks @achinta. It is possible that you can customize the image segmentation template to add a fuzzy search above the classes column. We'll keep a note of this for our image segmentation interface roadmap.

**Comment by Riegerb** [comment]
As @casainfinita  said, you can create a labeling interface to include search functionality directly embedded in the interface. See [Creating Custom Labeling Interfaces](https://github.com/Labelbox/Labelbox#creating-custom-labeling-interfaces) for more information and examples of creating a custom labeling interface.

If you have any questions about building a custom interface, please let @danielrasmuson or myself know.

**Comment by manuaero** [comment]
You can now search for classes in Image segmentation interface.
