### ISSUE TITLE
Unable to export annotations

### ISSUE THREAD

**Issue by achinta** [Labelbox/Labelbox#24]
In this example, there are three images for segmentation. 
![image](https://user-images.githubusercontent.com/1024878/35956848-1b2aaf1a-0cbe-11e8-8a46-023f9243d0b0.png)

But we see that there are 10 labels to be exported (which were labelled before adding cars.csv)
![image](https://user-images.githubusercontent.com/1024878/35956878-4a60deee-0cbe-11e8-8f0a-2ab3b6ab0e3d.png)

When I click on 'start labelling', we get the message 'No more items to label'
![image](https://user-images.githubusercontent.com/1024878/35956935-a88392e6-0cbe-11e8-9053-a49ddef5d228.png)

**Comment by danielrasmuson** [comment]
Hi @achinta, I just pushed an update. Could you check and see if that fixed your problem?

**Comment by danielrasmuson** [comment]
I had to temporarily pull this bug. Will let you know when its back outl.

**Comment by danielrasmuson** [comment]
Hi @achinta, this should be working for you now.
