### ISSUE TITLE
How to realize multi-label image classification annotation?

### ISSUE THREAD

**Issue by SkyCASIA** [Labelbox/Labelbox#25]
Thanks for checking this issue!
My problem is: how to realize multi-label image classification annotation, given that we want to assign multi-label to each single picture? Is there any alternative (e.g., assign multi-label to a single image with a single page) rather than starting several single-task image classification annotation procedure?

**Comment by danielrasmuson** [comment]
We don't currently have a out of the box multi-label classification template (though we might soon) but it's easy to make your own!

Here is an example.

<img width="340" alt="screen shot 2018-02-09 at 9 07 16 pm" src="https://user-images.githubusercontent.com/4013767/36058746-988e8e66-0ddd-11e8-91fc-69345a884815.png">

```html
<script src="https://api.labelbox.io/client/v0.1/labeling-api.js"></script>
<img src="" width="300px" />
<div style="display: flex; margin-top: 20px">
  <div >
    <div>Type of Car</div>
    <form action="" id="type">
      <input type="radio" name="type" value="modelx">Model X</input><br>
      <input type="radio" name="type" value="models">Model S</input><br>
    </form>
  </div>
  <div style="margin-left: 100px">
    <div>Color</div>
    <form action="" id="color">
      <input type="radio" name="color" value="red">Red</input><br>
      <input type="radio" name="color" value="blue">Blue</input><br>
      <input type="radio" name="color" value="orange">Orange</input>
    </form>
  </div>
</div>
<button onclick="submit()">Submit</button>

<script>
function getValueOfForm(formSelector) {
  return Array.from(document.querySelector(formSelector).querySelectorAll('input')).find((elem) => elem.checked).value;
}

function clearForms(){
  Array.from(document.querySelectorAll('input[type="radio"]')).forEach((radio) => {
    radio.checked = false;
  });
}

function setNextImage(){
  Labelbox.fetchNextAssetToLabel().then(function(imageUrl){
    document.querySelector('img').src = imageUrl;
  });
}

function submit(){
  var type = getValueOfForm('#type');
  var color = getValueOfForm('#color');
  if (type && color) {
    Labelbox.setLabelForAsset(JSON.stringify({type, color}));
    setNextImage();
    clearForms();
  } else {
    alert('Please set both type and color');
  }
}

setNextImage();
</script>
```

Here are the [full docs](https://github.com/Labelbox/Labelbox#labelbox-pluggable-interface-architecture) for our local development.

**Comment by SkyCASIA** [comment]
Thanks for the code for reference!

**Comment by fera0013** [comment]
I need that features for segmentation, i.e. I have to fiddle with the more powerful, but also more involved React template. Is there multilabel - example for the segmentation case, as well?
