### ISSUE TITLE
Adding Collaborators with multiple OAuth

### ISSUE THREAD

**Issue by pshah123** [Labelbox/Labelbox#26]
**Using:** `labelbox.io` (2/11/18)

**Steps to reproduce:** User links with Google OAuth or GitHub OAuth. User then accepts email invite to collaborate and sets password. User does not see project and has to sign out/sign in with email to get the project.

**Likely Issue:** OAuth bug

Thanks--.

**Comment by casainfinita** [comment]
Hi @pshah123, thanks for sharing this. We can reproduce this and working on the fix.

**Comment by danielrasmuson** [comment]
Hi @pshah123,

I'm excited to say we just released a feature where if we already have an account with the same email we will prompt to link the accounts.

<img width="260" alt="screen shot 2018-02-21 at 10 04 59 pm" src="https://user-images.githubusercontent.com/4013767/36522781-4ac4199c-1753-11e8-96aa-406c1ae3f9f8.png">

Thanks for reporting this issue.
