### ISSUE TITLE
Labels don't reselect

### ISSUE THREAD

**Issue by pshah123** [Labelbox/Labelbox#27]
Using: `labelbox.io` (2/12/18)

Steps to reproduce:
1. Select label
2. Draw bounding box

Expected: Label stays selected and can draw multiple bboxes
Actual: Label deselects and must be reselected forcibly

**Comment by casainfinita** [comment]
@pshah123  Thanks. We are going to make some improvements to save time while labeling and consider this.

**Comment by casainfinita** [comment]
@pshah123  we've added keyboard shortcuts for selecting the classes. I believe it makes the classes selecting/switching a lot faster and the reduces the need to keep the tool activated. Let me know what you think.

**Comment by pshah123** [comment]
Works great!
