### ISSUE TITLE
Add data to project via API

### ISSUE THREAD

**Issue by fera0013** [Labelbox/Labelbox#28]
Instead of uploading a set of images or defining the specific path to images in a config file, I would like to be able to enter a specific combination of search terms and automatically get the corresponding images via the google search api. 

This feature could be easily implemented by using one of the following node modules:

https://www.npmjs.com/package/node-google-image-search

https://www.npmjs.com/package/node-google-image-search

You could then pipe the received image urls to a csv file and use the workflow you have already implemented.

**Comment by casainfinita** [comment]
@fera0013 Thanks -- at the very least, it could be very interesting to have a script/tool that scraps google images and creates a CSV file to import into Labelbox.

**Comment by fera0013** [comment]
I got a script that generates such a csv file based on arbitrary search queries - it's in python, however...

**Comment by casainfinita** [comment]
@fera0013  amazing! We are architecting a job system where we will be able to run python scripts Labelbox in the future. We will use this as a test.

**Comment by manuaero** [comment]
We have data import API here: https://docs.labelbox.com/import
It should be possible to do this now.
