### ISSUE TITLE
Support multidimensional labelling 

### ISSUE THREAD

**Issue by fera0013** [Labelbox/Labelbox#29]
Multidimensional labelling, i.e. the attachment of one label for each dimension out of a D-dimensional labelset for each sample is not supported yet. 

A somewhat contrived example would be a 2 dimensional labelset, where one Dimension would consist of the labels male/female and the second dimension of the labels human/animal.  When labeling the examples, each images should receive a label from each dimension.

**Comment by danielrasmuson** [comment]
Hi @fera0013,

I agree, I think this is a feature we should support out of the box. In the meantime this is certainly something that you could use a custom template to accomplish.

Please this thread #25 for an example.
