### ISSUE TITLE
Text classification template

### ISSUE THREAD

**Issue by manuaero** [Labelbox/Labelbox#3]
Build an example text classification starter template.

**Comment by danielrasmuson** [comment]
I'm excited to say we just released a text classification template.

You can find the code here.
https://github.com/Labelbox/Labelbox/tree/master/templates/text-classification

Here is an example
<img width="703" alt="text-classification" src="https://user-images.githubusercontent.com/4013767/35461506-0b32b9b6-029d-11e8-8b48-c9346d13e161.png">

And as always the template can be forked or customized directly in labelbox.io
<img width="1440" alt="screen shot 2018-01-26 at 1 24 34 pm" src="https://user-images.githubusercontent.com/4013767/35461521-18ada36c-029d-11e8-9225-6d8b10a0b6b6.png">

Feedback welcome.
