### ISSUE TITLE
Provide a semantic segmentation template for multidimensional labeling

### ISSUE THREAD

**Issue by fera0013** [Labelbox/Labelbox#31]
The template introduced in this [thread](https://github.com/Labelbox/Labelbox/issues/25) demonstrates, how each dataset instance can be taged with multiple labels at the same time. Unfortunately, this template only works for the simple image detection case. For semantic segmentation the  [React template](https://github.com/Labelbox/Labelbox/tree/master/templates/image-segmentation) has to be used, which is a bit more involved, especially since it is not very well documented. 

Please provide an example for multidimensional semantic segmentation, similar to https://github.com/Labelbox/Labelbox/issues/25.

**Comment by casainfinita** [comment]
@fera0013  Yeah, we might build a generic solution for hybrid templates soon.

**Comment by fera0013** [comment]
What do you mean by "hybrid templates" ?

**Comment by casainfinita** [comment]
@fera0013  I meant that one would be able to segment and classify images in a single template.

**Comment by Riegerb** [comment]
Hey @fera0013, there is now a classification + segmentation labeling interface available in Labelbox. Does it suit your needs?
