### ISSUE TITLE
Image segmentation labelling trouble

### ISSUE THREAD

**Issue by francoto** [Labelbox/Labelbox#34]
Hello, 
I'm trying out Labelbox to see if I will use it for the future.
I add this issue:
when I create a polygon, setting new points, if I keep the mouse button pressed to move the picture, it actually remove the last point I set **before** keeping the button pressed. 
This is really frustrating when I'm doing precise annotation on zoomed area because I actually need to do this for almost every point.

Could you imagine another way to handle moving picture and creating point ? For example by using modifier like space key or control key to disambiguate the two actions.

Best regards,

**Comment by Riegerb** [comment]
Hey Francoto -

I'm not able to reproduce this behavior. When the mouse is held down, the previous points should not be deleted, and the image should be dragged.  Which browser/version are you using?

**Comment by francoto** [comment]
Hey Riegerb,
I'm sorry I can't reproduce what I was describing either. I'm using Firefox 59.0.
I guess a recent browser update fixed this behaviour.
