### ISSUE TITLE
Delete skipped images before exporting

### ISSUE THREAD

**Issue by achraf-boussaada** [Labelbox/Labelbox#38]
Hi, 

I think it would be a good idea to give the user the possibility to delete the skipped images or ignore them before exporting.. because 
first : if they're skipped than probably they have no use 
second : when I try to convert a JSON file to Pascal VOC the conversion stops after finding the first skipped file.

Here is the error : 
`Traceback (most recent call last):
  File "json_to_voc.py", line 18, in <module>
    images_output_dir=images_output_dir, label_format='XY')
  File "/Users/aboussaada/Desktop/labelbox/Labelbox/scripts/labelbox2pascal/__init__.py", line 76, in from_json
    for cat in data['Label'].keys():
AttributeError: 'unicode' object has no attribute 'keys'`

keep up the good work.

**Comment by manuaero** [comment]
Thanks @achraf-boussaada , Great point. We've had users who explicitly like to see skipped images in export. I think there is a good solution i.e. we might consider adding a simple toggle. Regardless, we will fix the JSON to Pascal VOC conversion asap. thanks for the information. Very helpful.

**Comment by danielrasmuson** [comment]
Hi @achraf-boussaada,

This is something we are planning on adding in the future.

Here is easy way you can filter it out on your side.

```shell
brew install jq # https://stedolan.github.io/jq/download/
cat <my-export.json>  | jq -c '[ .[] | select(.Label != "Skip") ]' > my-export-without-skip.json
```

Replace `<my-export.json>` with the filepath of your labelbox export.
