### ISSUE TITLE
Deactivation and deletion of collaborator

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#40]
I have entered one collaborator with wrong email and now I see such collaborator. Now way to remove collaborator. In future I probable will need to deactivate some collaborator for some reason.

**Comment by danielrasmuson** [comment]
Thanks @valeriyvan. This is a feature we are planning on adding in the future. If you let me know the email or send us a message in our on site chat I'll get that user removed from your organization.

**Comment by valeriyvan** [comment]
Ok. I am sending you message in chat. Thank you.

**Comment by Riegerb** [comment]
See existing issue #17. Contact Labelbox support (support@labelbox.io) to have collaborators deleted in the meantime until this feature is added to Labelbox.
