### ISSUE TITLE
Aligning of classes in labeling

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#41]
Look how classes are looking in my project:
![labelbox-screenshot1](https://user-images.githubusercontent.com/1630974/38288222-a758ecc2-37cf-11e8-9eb9-03f18078c5e4.jpeg)

I guess it's better to left align class names.

**Comment by danielrasmuson** [comment]
Hi @valeriyvan, thanks for the feedback. I just pushed a fix. Let me know if that resolves your issue.

**Comment by valeriyvan** [comment]
Now it looks beautifully! Thanks a lot!
