### ISSUE TITLE
Add [approve / reject] functionality to review mode

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#42]
Review mode is not working or I don't understand how to use it.
Reset and Save buttons are always inactive both in Safari and Chrome.

**Comment by danielrasmuson** [comment]
Is Reset / Save still disabled after you make a modification to the label? I.E. delete or add an annotation?

At the moment review mode mostly functions as a way to quickly jump through the labels your team created. What functionality would you like to see in review mode?

**Comment by valeriyvan** [comment]
Ups. I thought I could look each image and approve if labeling is correct or reject otherwise. Now I get it why Reset and Save buttons are always inactive.

About this
> At the moment review mode mostly functions as a way to quickly jump through the labels your team created. What functionality would you like to see in review mode?

I am going to create separate issue (feature request). I have about 400 label classes (on one image I have only 1-10 of them, average is about 3, I guess). Currently reviewing if labeling is done correctly takes more time then labeling itself. I have to scroll list of 400 label classes up and down many-many times.

I have some ideas how to improve labeling and reviewing in project with number of classes taking more then one screen.

**Comment by danielrasmuson** [comment]
Yea please share your feedback.
