### ISSUE TITLE
"Labels created ..." is data rows labeled, not total annotation count

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#44]
Graph 'Labels created by collaborator' shows not labels per collaborator, but count of images labeled per collaborator.

Same problem in performance table. It says Labels when showing Images counts.

That's confusing.

**Comment by Riegerb** [comment]
Hey @valeriyvan, 'Labels created ...' is a count of data rows labeled and not annotations. Do you have a suggestion on a better wording for this?

**Comment by danielrasmuson** [comment]
Yea maybe we could improving our wording. Right now if a user draws three bounding boxes on an image they made 3 annotations but one label.
