### ISSUE TITLE
Image orientation bug

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#46]
This image has correct orientation:
[CA4B0901-BECC-4055-BC28-ECA49EC65A8D.jpg](http://w7software.com/downloads/traffic-signs-ukraine/batch1/CA4B0901-BECC-4055-BC28-ECA49EC65A8D.jpg)

But here's how it's shown in the labelbox:
![screenshot](https://user-images.githubusercontent.com/1630974/38569611-0690969c-3cec-11e8-96ac-00adad052481.jpeg)

I guess you don't respect orientation in EXIF header.

**Comment by valeriyvan** [comment]
And to find which exactly image is shown incorrectly I had to look into page source. It should be easier way to look for image URL!

**Comment by manuaero** [comment]
@valeriyvan, you are correct, we don't read the orientation in EXIF header yet. Meanwhile, I recommend that you read the EXIF data and orient images as such before training a model. We will likely handle this in coming weeks.

**Comment by euwest** [comment]
>I guess you don't respect orientation in EXIF header

I can confirm that we don't currently parse exif (and neither does the browser), and so exif-based rotations won't be applied. parsing exif (and saving it to the label) is something we're considering, but we don't have a timeline for that work yet
