### ISSUE TITLE
Navigation in review goes in images of already deleted dataset

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#47]
![screenshot](https://user-images.githubusercontent.com/1630974/38649798-da7eae96-3df8-11e8-9859-f87f60758da8.jpeg)
If here I navigate over Outline listed objects it's possible to go on images of already deleted dataset. URLs to images from deleted dataset work because I have deleted dataset (which actually just deletes CSV file), but images are hosted on my own server and are still there.

**Comment by danielrasmuson** [comment]
Are you saying you can see labels from deleted datasets in the review screen?

**Comment by valeriyvan** [comment]
I guess so. Could say that for sure when I will accomplish labeling current batch of 1000 images and start new one in about a week.

**Comment by danielrasmuson** [comment]
Hi @valeriyvan, I'd be happy to look into this. Could you give me steps to reproduce.
