### ISSUE TITLE
Align labeled images counter in class card on labeling interface

### ISSUE THREAD

**Issue by nastyavan** [Labelbox/Labelbox#48]
It would be easier to read if counters would be right aligned.

![untitled](https://user-images.githubusercontent.com/24795485/38568976-ba97a81e-3cf2-11e8-9bf6-e37acedf7b77.png)

**Comment by danielrasmuson** [comment]
Hi @nastyavan,

Thanks for the feedback. I've just updated our segmentation template to be right aligned.

<img width="1438" alt="screen shot 2018-04-11 at 12 25 12 pm" src="https://user-images.githubusercontent.com/4013767/38638538-713daf24-3d83-11e8-8ab6-a9b4cffddadd.png">

**Comment by nastyavan** [comment]
Looks much better, thank you!
