### ISSUE TITLE
The layout of labeling interface breaks if image uploading error occurs.

### ISSUE THREAD

**Issue by nastyavan** [Labelbox/Labelbox#49]
1. The page of image that wasn't uploaded.
https://image-segmentation-hybrid.labelbox.io/?project=cjfbrjj7vacct01864jbby0pl
http://w7software.com/downloads/traffic-signs-ukraine/batch1/7D6657C1-E1AF-42CB-AA23-3E799EB7358D.jpg

![layout bug](https://user-images.githubusercontent.com/24795485/38576831-e62461ba-3d07-11e8-9843-fb567345237c.jpg)

2. All following image pages contain image uploading error.
https://image-segmentation-hybrid.labelbox.io/?project=cjfbrjj7vacct01864jbby0pl

![layout bug_2](https://user-images.githubusercontent.com/24795485/38577037-7689360e-3d08-11e8-944a-ef21e75700e3.jpg)

**Comment by danielrasmuson** [comment]
Hi @nastyavan, I've just pushed a change to fix this issue. Let me know if you continue to see it.
