### ISSUE TITLE
Support for keyboard shortcuts in the templates

### ISSUE THREAD

**Issue by casainfinita** [Labelbox/Labelbox#5]
For faster data labeling

**Comment by danielrasmuson** [comment]
I'm excited to say our segmentation template now includes keyboard shortcuts. Please let us know if you would like to see any additional shortcuts added.

<img width="397" alt="screen shot 2018-02-10 at 8 53 16 pm" src="https://user-images.githubusercontent.com/4013767/36069766-74a5b5ac-0ea4-11e8-94c7-2c74286aab27.png">
