### ISSUE TITLE
Automated upload of a new .csv file

### ISSUE THREAD

**Issue by alexanderroot** [Labelbox/Labelbox#51]
To maintain a constant source of data, I would like to have some sort of automation capability to have a python interface with the website. Basically, to have a timed script (biweekly) that updates which URLs I have on Labelbox.

**Comment by manuaero** [comment]
@alexanderroot  yes, we do have APIs that one can use to add or append data -- they come in enterprise tier.

**Comment by manuaero** [comment]
@alexanderroot see our API docs here: https://docs.labelbox.io/
