### ISSUE TITLE
Dismissed task bar appears on every login

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#52]
![screenshot-dismiss](https://user-images.githubusercontent.com/1630974/38723224-4cdde592-3ef8-11e8-9775-deab20306323.jpeg)
Dismissed task bar appears on every login.
Seems to be bug.

**Comment by danielrasmuson** [comment]
Hi @valeriyvan, we just released an update that moves the taskbar to the toolbar.

![screen shot 2018-04-13 at 5 07 33 pm](https://user-images.githubusercontent.com/4013767/38762099-4cd588ee-3f3d-11e8-95f1-4545ba621c57.png)
