### ISSUE TITLE
Export data

### ISSUE THREAD

**Issue by jameschartouni** [Labelbox/Labelbox#53]
Would you be able to create an option on the export data screen to not include "skipped images" in the json/csv file?

**Comment by danielrasmuson** [comment]
Hi @jameschartouni,

This is something we plan on adding in the future.

Here is easy way you can filter on your side.

```shell
brew install jq # https://stedolan.github.io/jq/download/
cat <my-export.json>  | jq -c '[ .[] | select(.Label != "Skip") ]' > my-export-without-skip.json
```

Replace `<my-export.json> with the filepath of your labelbox export.

**Comment by danielrasmuson** [comment]
James I'm going to close this issue so we can keep this conversation in once place --> #38 

More feedback welcome.
