### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by jameschartouni** [Labelbox/Labelbox#54]
I currently have a bunch of .csv files being uploaded, but seemed to have been stalled under 'tasks.' How would I be able to clear the queue of .csv files being processed by labelbox?

**Comment by danielrasmuson** [comment]
Hi @jameschartouni, sorry about that. I completed the tasks in your account. We are working on our improving our importing system. Please reach out in our chat if you hit any problems in the future. We are here to help.
