### ISSUE TITLE
Button + shortcut to rescale and reposition image to original scale/position

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#55]
Having many labels of different size in one image to make bounding precise you have to rescale and drag image many times. Returning image to original scale/position to check if everything was labeled needs several rescales and drags. Would be nice to have a button and/or shortcut to return image to original scale/position.

**Comment by danielrasmuson** [comment]
Good idea.

**Comment by valeriyvan** [comment]
Any plans for implementing this?

**Comment by euwest** [comment]
pressing z while a segmentation is selected will zoom to it, but if you've got nothing selected z will zoom you out to original scale. if you're way zoomed out, you can zoom in then hit z to rescale to original scale
