### ISSUE TITLE
Icons for classes

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#56]
I have about 400 different classes in my project which looks like:
![screenshot11](https://user-images.githubusercontent.com/1630974/38897986-b5b7ac0c-4294-11e8-8848-4ab388d2eaaf.jpeg)

It's very difficult to find appropriate class in list of classes.

Having icons for each class, like on screenshot below, would ease looking for appropriate class:
![img_8899](https://user-images.githubusercontent.com/1630974/38898463-6567ce8e-4295-11e8-80c1-b257658715ec.png)

Think of adding optional URI for icon for class to JSON.

**Comment by manuaero** [comment]
Hi @valeriyvan, since this is not a common request, I recommend that you modify the labeling interface template to show icons.
