### ISSUE TITLE
Button + shortcut for showing classes above of bounding boxes

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#57]
Having hundreds of classes makes (self)reviewing extremely time-consuming.
Look on screenshot below and imagine how much scrolling have you to do to check that every item was labelled correctly:
![screenshot12-hidden](https://user-images.githubusercontent.com/1630974/38900038-4c0ee058-429a-11e8-8e3c-59cec6333dbb.jpeg)

But having button and/or shortcut which will show classes above each bounding box could make reviewing easy:
![screenshot12-hidden-labeled](https://user-images.githubusercontent.com/1630974/38900100-8128ca10-429a-11e8-96bb-1d44527ed823.jpeg)

In review mode these classes could be shown by default. When in usual labelling mode button and/or shortcut to show/hide classes might be useful.

**Comment by manuaero** [comment]
Yeah that makes sense. Perhaps we can also sort the classes with labels on the top.

**Comment by valeriyvan** [comment]
Unfortunately, what we have in label box now makes validation barely viable when you have more then a hundred of classes.

**Comment by ryanquinn3** [comment]
@valeriyvan 

We added a new hotkey, the period key, that should help you with this problem. While the key is pressed, a text popup will appear on top of all the annotations on your screen.

<img width="1511" alt="screen shot 2018-07-11 at 1 39 42 pm" src="https://user-images.githubusercontent.com/5115565/42598146-2f9caa96-8510-11e8-97a7-9058aa79491e.png">

Hopefully this serves a temporary solution for you problem. We hope to enhance the UI to better serve this need in the future.

**Comment by ryanquinn3** [comment]
@valeriyvan I've confirmed that the feature is deployed. Are you trying to use the feature while in review mode? If so, you may need to click in to the right side of the screen (the segmentation view) for the hotkey to work properly.

**Comment by valeriyvan** [comment]
No, it is not working neither in labelling nor in reviewing.

**Comment by danielrasmuson** [comment]
@valeriyvan. Sorry Valeriyvan.

This feature is only available in "Image Segmentation V3"

<img width="437" alt="screen shot 2018-07-12 at 12 08 13 pm" src="https://user-images.githubusercontent.com/4013767/42654113-59ef1966-85cc-11e8-861b-151ffe43a911.png">

You can easily move an existing project to that template, but you'll notice that your labels will have two different formats

V2
```
buildings: [[x, y]]
```

V3
```
buildings: [{geometry: [x,y]]
```

**Comment by valeriyvan** [comment]
Any reason of not making this feature available everywhere?

**Comment by danielrasmuson** [comment]
We will be adding future improvements to the V3 template. Its fairly painless to upgrade. We just don't want to break anyone's scripts by automatically upgrading.
