### ISSUE TITLE
Wrong count and range of images in review mode

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#59]
Navigation on bottom shows '192-204 of 1008', when data set has exact 1000 images.
If the first of images shown is really 192nd, then the last shown is 203d, not 204th!
Thee numbers and two bugs. May that explains really weird navigation in review mode.
![screenshot14](https://user-images.githubusercontent.com/1630974/39095528-5fb21bc4-4642-11e8-8922-317720fe71a4.jpeg)

**Comment by casainfinita** [comment]
Thanks @valeriyvan, We will take a look at this soon.

**Comment by danielrasmuson** [comment]
Hi @valeriyvan, sorry you hit this problem. This should now be resolved for all future datasets.
