### ISSUE TITLE
Export segmentation labels as mask tifs

### ISSUE THREAD

**Issue by kysolvik** [Labelbox/Labelbox#6]
Feature request: 
Add functionality to export image segmentation labels as mask images in tif or jpg format.

**Comment by Mikkolehtimaki** [comment]
Maybe include possibility to export each class as binary image for overlapping object handling. If there are multiple classes, that is.

**Comment by casainfinita** [comment]
We've added this feature! 
We generate image mask per label class i.e. If there are 2 car and 2 tree labels in an image, we will generate 2 image masks in total (car and tree). White pixels in the image mask represent the object.  

<img width="1012" alt="screen shot 2018-01-30 at 3 01 26 pm" src="https://user-images.githubusercontent.com/3059998/35658355-bdab7896-06b5-11e8-92e3-92176a67c1c5.png">
