### ISSUE TITLE
No More Items to Label Screen

### ISSUE THREAD

**Issue by jameschartouni** [Labelbox/Labelbox#61]
For two of my projects, including a newly uploaded one, when I want to start labeling new images I get the "All Done!" pop up screen notifying me of no more items to label. Each project has about 80,000 images with fewer than 100 images labeled. Did I configure something incorrectly?

**Comment by danielrasmuson** [comment]
Hi James, We are still fixing some issues with auto audit. If you have that enable I would recommend turning it off until we remove the beta flag. Sorry for the issue. We are working on resolving this.

**Comment by danielrasmuson** [comment]
We have improved the beta of auto audit. Please let me know if you see this again.
