### ISSUE TITLE
Some questions of EXPORT

### ISSUE THREAD

**Issue by SkyCASIA** [Labelbox/Labelbox#62]
There are some problems when I attempt to convert the exported .json / .csv file into the desired format:
1. Can we decide whether to export data labeled as _Skip_ ?
2. Can the comma between each data label be replaced with other marks (e.g., ; or \n) ? I believe this small step can bring much convenience and free us from tedious format conversion process ...
3. Export the labels according to the latest labeling interface in case of some necessary changes of labeling interface during annotation process.

Thanks!

**Comment by jameschartouni** [comment]
If I understand the third point correctly, does that mean that if you add another feature, it won't adjust the label IDs in the image accordingly? Is there an option where you can hardcode the label id so that it is consistent across datasets?

**Comment by manuaero** [comment]
@SkyCASIA 
1. Yes, we might add this soon. Is it not useful to know the skipped items in an export? Or its just an annoyance to remove skipped labels in python?

2. Could you please provide a brief example? Output is a JSON and could be loaded as a dict in python

3. Hmmm.. if you change labeling schema in the project, you want all previous labels to be exported under new labeling schema?

**Comment by feynmanliang** [comment]
Cleaning up inactive issues, please reopen if the problem is not resolved!
