### ISSUE TITLE
Wrong count of raws in CSV

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#64]
Count shown as count of raws includes title line:

![screenshot16](https://user-images.githubusercontent.com/1630974/39882417-0491e710-5484-11e8-9d5f-24d99a384d64.jpeg)

I guess it's a bug.

**Comment by manuaero** [comment]
Good find, @valeriyvan

**Comment by SkyCASIA** [comment]
Besides, another potential bug I've met twice recently is that: the number of annotated data in the exported .csv file is **MORE THAN** the number of labels shown online (i.e., # labeled + # skipped).
In my case, I can export 4146 labels in the exported .csv file, larger than 4138, which is the number of labels given online.
Have you guys ever met this confusing situation ?

**Comment by danielrasmuson** [comment]
We recently pushed a fix for this issue. Feedback welcome.
