### ISSUE TITLE
Use multiple CSV fields when labeling data

### ISSUE THREAD

**Issue by dsalfran** [Labelbox/Labelbox#68]
Let's assume I have two "text" columns in a CSV file: `colA` and `colB`. The first column contains the labels of the text in the second column. How do I get labelbox to show both values and ask if the value from `colA` is the label of `colB`?

**Comment by danielrasmuson** [comment]
I would include them both in the same cell.

If you current format looks like

A (text)    |      B (label)
---------------------
hi             |  greeting
hello        | greeting
goodbye | farewell

A combined format could look like

Information to Verify
---------------------
Label: greeting Text: hi  
Label: greeting Text: hello 
Label: farewell  Text: goodbye 

Would that fit your usecase?

**Comment by danielrasmuson** [comment]
More discussion welcome.
