### ISSUE TITLE
How to drag while creating a polygon?

### ISSUE THREAD

**Issue by Mikkolehtimaki** [Labelbox/Labelbox#7]
If I need to drag the image to one direction or other, while creating a polygon annotation, a new data point will be created. Especially inconvenient if I have to zoom in while creating a polygon and now I need to drag to see the previous data point.

To duplicate:

1. start creating a polygon
2. zoom in
3. try to drag the screen

You always end up with an unintended data point. You can click the "delete last point, but it really slows down the process.

So question is, how to drag while creating a polygon?

**Comment by casainfinita** [comment]
We've added dragging in our new segmentation template. There's some improvements to be made in rectangle tool so that it works similar to polygon tool.
