### ISSUE TITLE
Are TIFF files unsupported?

### ISSUE THREAD

**Issue by jaybo** [Labelbox/Labelbox#70]
TIFF files are added to a Data Source without error, but upon retrieval I'm getting the following error message:

Error loading https://firebasestorage.googleapis.com/v0/b/labelbox-193903.appspot.com/o/cjhch2ltx0mc10108kwjdj64u%2F1a6fbbeb-1b92-49ff-b493-302e1ea072f6%2F20180218135731773_247488_8R_Tape070D_03_001924_0_22_22.tif?alt=media&token=24b38f63-5bf4-4024-8a5d-4c50bef74cb7. Please confirm that this url is live and a direct link to an image. Webpage links are not supported.

A .png of the same image seems to work fine.

**Comment by danielrasmuson** [comment]
Hi @jaybo, correct TIFF files are not supported in the default templates. The default support templates currently support image formats that can be loaded an html `img` tag, https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Supported_image_formats.

Its worth noting that the template could be forked and support could be added https://github.com/Labelbox/Labelbox#creating-custom-labeling-interfaces.

Happy to hear if others would like TIFF file support.

**Comment by danielrasmuson** [comment]
More discussion welcome.
