### ISSUE TITLE
Wrong Date Created sorting order in Activity table

### ISSUE THREAD

**Issue by valeriyvan** [Labelbox/Labelbox#71]
![screenshot17](https://user-images.githubusercontent.com/1630974/40299895-009ea05a-5ce8-11e8-9abe-38d677d67a80.jpeg)
It seems like sorting order is wrong!

**Comment by danielrasmuson** [comment]
Thanks for bringing this up. We are working on a fix.

**Comment by danielrasmuson** [comment]
Hi @valeriyvan, Thank you for reporting this issue. We just pushed a fix. Feedback welcome.
