### ISSUE TITLE
The order of data in ACTIVITY makes it hard to review or correct those recent annotations

### ISSUE THREAD

**Issue by SkyCASIA** [Labelbox/Labelbox#72]
After the latest update, the order of labeled data in **ACTIVITY** makes it _difficult_ for our annotators to review their last annotations, and therefore causes unexpected trouble for annotators to correct their annotations ...

**Comment by valeriyvan** [comment]
Duplicate of #71

**Comment by danielrasmuson** [comment]
Thanks for bringing this up. We are working on a fix.

**Comment by danielrasmuson** [comment]
Hi @SkyCASIA and @valeriyvan, we just pushed a fix for this issue. Feedback welcome.
