### ISSUE TITLE
Project overview doesn't show label statistics

### ISSUE THREAD

**Issue by pkdogcom** [Labelbox/Labelbox#73]
It seemed to me that there were once label statistics, such as how many images belong to each label, in the project overview page, which is really helpful for analyzing what data we need to collect further. But I am not able to find a way to have the statistics shown on that page anymore. Is it something wrong in my project configuration or this feature is just not available yet?

**Comment by danielrasmuson** [comment]
Thanks for reporting this issue. I've also experienced the syncing for the dashboard reports to be very slow. I.E. It could take up to a few minutes for a label to show up on the dashboard reports.

We are presently actively working on this problem and I'll followup with updates.

**Comment by danielrasmuson** [comment]
I misunderstood. Will follow up.

**Comment by manuaero** [comment]
Hi @pkdogcom, 

We found out that we don't support statistics on the image classification interface. Its an old interface and is superseded by a new one called "Image Segmentation V3". You can customize this interface to only have classification. I recommend you switch to the new interface. thanks.
