### ISSUE TITLE
Point to Locally Stored Data.

### ISSUE THREAD

**Issue by Shrsh** [Labelbox/Labelbox#75]
I want to create a custom labelling interface through which I want to point to my images that are stored locally. I don't want to upload my data on cloud. Can you help me with that? Thanks!.

**Comment by danielrasmuson** [comment]
Hi @Shrsh, for sure you can do this.

Here is a tutorial on how to use on premise data with Labelbox.
https://github.com/Labelbox/Labelbox/blob/master/docs/on-premise-data.md

Here is how you can create a custom interface.
https://github.com/Labelbox/Labelbox#creating-custom-labeling-interfaces

And here is the labeling.js reference
https://github.com/Labelbox/Labelbox/blob/master/docs/api-reference.md

Hope that helps! Let me know if I can provide more information.

**Comment by Shrsh** [comment]
Hi @danielrasmuson  Thanks for the help. 
It's giving out this error
"Error loading 192.168.0.15:3000/donut-10.jpeg. Please confirm that this url is live and a direct link to an image. Webpage links are not supported."
I'm able to access image using this url in my browser. But LabelBox can't point to this image and gives this error. 
Thanks!

**Comment by danielrasmuson** [comment]
Try with http before the url, http://192.168.0.15:3000/donut-10.jpeg

**Comment by Shrsh** [comment]
Thanks! It worked
