### ISSUE TITLE
How to deploy label box locally?

### ISSUE THREAD

**Issue by Han-Gang** [Labelbox/Labelbox#76]
Hello,

I found that there is no installation guide for label box, I don't know how to deploy it locally on my ubuntu 16 server, does anyone help me with this?

Thanks,
Han, Gang

**Comment by danielrasmuson** [comment]
Hi @han-gang, currently only the labeling frontends are open source. So you would need to hookup your own backend if you dont host on labelbox.

**Comment by danielrasmuson** [comment]
Feedback welcome.
