### ISSUE TITLE
Enable end-to-end classification labeling only using keyboard shortcuts

### ISSUE THREAD

**Issue by bkanuka** [Labelbox/Labelbox#78]
Similar to what exists in the Segmentation interface (see bug #5 ). The entire image should be classified using a keyboard shortcut.

**Comment by danielrasmuson** [comment]
This is good feedback. We are planning on adding this feature in the future.

**Comment by euwest** [comment]
This has been added; classifications can be selected and manipulated with keyboard shortcuts now, similar to how segmentation tools can be
