### ISSUE TITLE
After labeling everything, it takes forever to load project overview and won't be able to export anything

### ISSUE THREAD

**Issue by ZixuSmartAg** [Labelbox/Labelbox#79]
I've tried many times, every time after I finishing labeling the dataset, the project overview will just take forever (even half an hour for just 3 images) to load and the export page says 0 labels. Please fix this immediately, we've wasted huge amount time on this.

**Comment by danielrasmuson** [comment]
Looking into this.

**Comment by danielrasmuson** [comment]
Currently you need to reload the page for the labels to update. Could that be your problem?

**Comment by danielrasmuson** [comment]
I believe this is now its now resolved, please let me know if your still experiencing issues.

**Comment by ZixuSmartAg** [comment]
[https://imgur.com/a/6fDnvHT](url)
Hi, thanks for your reply, however, I think this is still happening and reload my page won't help. To visualize what's going on I've uploaded a gif to this link above. So after I finish labeling, the overview takes forever to reload and reloading it will just start all over and all my labels are not even saved.

**Comment by danielrasmuson** [comment]
Hi @ZixuSmartAg, If you look in that configure screen you'll see a "Preview Mode" header. Any labels created in that mode aren't saved. If you click "Confirm" and then "Start Labeling" your labels will then be saved.
