### ISSUE TITLE
how do I convert Labelbox JSON export to Pascal VoC format?

### ISSUE THREAD

**Issue by anamissblonde** [Labelbox/Labelbox#83]
I dont understand how to convert my JSON data to Pascal voc format. Help please!

**Comment by Riegerb** [comment]
Hey @anamissblonde, see the docs here: https://github.com/Labelbox/Labelbox/tree/master/scripts

Does that help?

**Comment by feynmanliang** [comment]
I'm going to close this issue for now. If it's not resolved, please let me know and I'll be happy to repoen!
