### ISSUE TITLE
Request: Mask Variables

### ISSUE THREAD

**Issue by hgrov52** [Labelbox/Labelbox#84]
It would be extremely helpful to have variables for each mask drawn by the user. For example, if a user were to draw a mask around a person, this feature would allow them to add a custom set of values to describe the mask like { "is_walking" : true, "Name" : "smith" }. This would allow the user to create one type of mask and apply variables to it, rather than having to go through the effort of creating a mask for each attribute. 

Thanks for the program, hopefully you are able to add this in the near future!

**Comment by manuaero** [comment]
Hi @hgrov52,

We just released support for nested labels and is available under Image Segmentation V3 interface. Here is an example JSON snippet for adding extra variables to a class. 

```json
{
      "name": "Car",
      "color": "navy",
      "tool": "polygon",
      "classifications": [
        {
          "name": "color",
          "instructions": "Select the car color",
          "type": "radio",
          "options": [
            {
              "value": "red",
              "label": "Red"
            },
            {
              "value": "blue",
              "label": "Blue"
            },
            {
              "value": "green",
              "label": "Green"
            }
          ]
        }
      ]
    }
```


![nested labels](https://user-images.githubusercontent.com/3059998/41994656-034a243a-7a04-11e8-8b09-ec1ab7c1e36d.gif)

**Comment by danielrasmuson** [comment]
Hi @hgrov52, please let us know your feedback.

**Comment by hgrov52** [comment]
That's exactly what I was looking for, thank you very much. This helps speed up my project a great deal. Thanks again for making this tool.
