### ISSUE TITLE
External ID shows "null" in exported json file

### ISSUE THREAD

**Issue by ZixuSmartAg** [Labelbox/Labelbox#86]
After I finish labeling, I downloaded the json file, but I found all the external ID are null. I'm not sure what caused this. Please help!

**Comment by danielrasmuson** [comment]
Did you add the external id when you uploaded the dataset?
<img width="458" alt="screen shot 2018-07-03 at 3 41 01 pm" src="https://user-images.githubusercontent.com/4013767/42247849-868f33c6-7ed7-11e8-960c-b0100fca11c9.png">

**Comment by ZixuSmartAg** [comment]
Hi, I think that's probably why my json file says null for external id. But when I was uploading it, it doesn't show me those options.
<img width="605" alt="screen shot 2018-07-05 at 3 32 34 pm" src="https://user-images.githubusercontent.com/39841301/42346829-7bcf2e9e-8069-11e8-8d87-1ad7a9b47335.png">

**Comment by manuaero** [comment]
@ZixuSmartAg you will have to add a an additional column for external id. Feel free to share the csv file over email and I can take a look.

**Comment by ZixuSmartAg** [comment]
@manuaero Hi, what do you mean by adding an additional column? Can you tell me how do I do it?

**Comment by manuaero** [comment]
@ZixuSmartAg here is the info on it: http://help.labelbox.com/adding-source-data-to-labelbox/on-premise-or-private-cloud-source-data

**Comment by yamarten** [comment]
I have the same problem when I upload local files in labelbox.com.  A month ago values of "External ID" were file names. Is this intended behavior?

**Comment by yamarten** [comment]
I got csv files with external IDs today. Thank you!

**Comment by manuaero** [comment]
@yamarten you're welcome!
