### ISSUE TITLE
Feature Request: Show collaborator roles

### ISSUE THREAD

**Issue by nimroha** [Labelbox/Labelbox#87]
Hi,
 
It would be easier for Admins if the Collaborators page had a "Role" column in the table
Now I have to click on every collaborator to see his/her role

thanks

**Comment by manuaero** [comment]
@nimroha Great idea. Will add soon.

**Comment by danielrasmuson** [comment]
Thank you for the feature request. We've recently added this.

<img width="1003" alt="screen shot 2018-08-16 at 5 03 29 pm" src="https://user-images.githubusercontent.com/4013767/44241049-57707200-a176-11e8-8481-6b6ae19c1ab9.png">
