### ISSUE TITLE
AttributeError: 'list' object has no attribute 'encode'

### ISSUE THREAD

**Issue by bilgan** [Labelbox/Labelbox#88]
I'm having an error on this line, which is that text is not a string its a list.

`text = text.encode('ascii')`

Please help. Thanks

**Comment by michel-meneses** [comment]
I was having the same error. I figured out in my case I should export the labels as **WKT**, not CSV.

**Comment by feynmanliang** [comment]
I think this may be a duplicate of #109 so I'm going to close this for now. If I'm mistaken, please let me know and provide repro instructions and I'll be happy to reopen!
