### ISSUE TITLE
ModuleNotFoundError: No module named 'labelbox2coco'

### ISSUE THREAD

**Issue by pallaviroyal** [Labelbox/Labelbox#89]
i followed steps from [here](https://github.com/Labelbox/Labelbox/tree/master/scripts).

**Comment by slothkong** [comment]
I guess  the `labelbox2coco` script is not for free

**Comment by GottliebFreudenreich** [comment]
`labelbox2coco` is in the Labelbox/scripts folder! You need to start your script from this folder or define the path in `import labelbox2coco`

**Comment by feynmanliang** [comment]
@GottliebFreudenreich is correct :) We haven't gotten around to creating a package for it so it's not available globally for import.

For now, you can either start your scripts from the `/scripts` folder, or append `/scripts` to your python path e.g. `PYTHONPATH=<path to Labelbox/scripts>:$PYTHONPATH python <path to your script>`.

I'm going to close this issue, but let me know if you still have problems!
