### ISSUE TITLE
Ability to review labeled data

### ISSUE THREAD

**Issue by casainfinita** [Labelbox/Labelbox#9]
Enable users to review labeled data and make corrections if needed.

**Comment by oliverdain** [comment]
It would also be nice if this included a "spot check" interface. Say I have 5 labelers on my team. I want to check in once/day and look at 5 random labels for each person so I can make sure they each understand the task.

**Comment by casainfinita** [comment]
Thanks @oliverdain, thats a good idea.

**Comment by casainfinita** [comment]
Hello all,

Excited to share that we have just added the ability to review land edit labeled data. 

To review or edit a label, go to activity tab inside your project, and click open. You can make changes to the label and hit save or clear your changes by hitting reset. 

We are soon going to add ability for you to review labels in labeling window by adding back button.

![review](https://user-images.githubusercontent.com/3059998/36685955-c3906996-1ad9-11e8-8e25-2256a3cca2be.gif)
