### ISSUE TITLE
Export issue - not exporting

### ISSUE THREAD

**Issue by alycege** [Labelbox/Labelbox#91]
Trying to export about 1200 rows and the export has been stuck like this for the last 20 minutes 
![screen shot 2018-07-10 at 11 05 43 am](https://user-images.githubusercontent.com/8033560/42519149-5f75a838-8431-11e8-9c6f-ff9b9db207be.png)

I've previously exported 2400 rows and it took only a few minutes 

UPDATE: exporting worked - just took about 2 hours

**Comment by manuaero** [comment]
Hi @alycege , exports can take some time. Expect much better performance in coming weeks.
