### ISSUE TITLE
Can I get the source code of Labelbox? Because our dataset is private!

### ISSUE THREAD

**Issue by LeoaY** [Labelbox/Labelbox#93]
Can I get the source code of Labelbox? Because our dataset is private!Thank You!

**Comment by danielrasmuson** [comment]
Hi @LeoaY.

We do offer on-premise data support for datasets that are private. https://github.com/Labelbox/Labelbox/blob/master/docs/on-premise-data.md

We also offer full on premise deployments for some enterprise engagements.
https://labelbox.com/enterprise

Hope that helps!

**Comment by danielrasmuson** [comment]
Feedback welcome.
