### ISSUE TITLE
Request: Landmark Labelling Interface

### ISSUE THREAD

**Issue by hartwoolery** [Labelbox/Labelbox#95]
I would like to be able to label landmarks on images (for example: https://i.stack.imgur.com/9bUgR.png).  Would configure project with a list of landmark names, and labels would be output in that order in normalized coordinates with label names shown on image as user adjusts landmarks.

**Comment by manuaero** [comment]
@hartwoolery I believe this is already possible. You can use point tool in our V3 segmentation interface.

**Comment by hartwoolery** [comment]
Thanks!  For future reference, it wasn't very obvious that this was possible from the template choices.  Maybe adding in a separate template for it would help clarify.

**Comment by manuaero** [comment]
Agreed -- thanks for the feedback. Will improve this in few weeks.

**Comment by hartwoolery** [comment]
After playing around a bit with it there would be a a very simple feature that would greatly streamline the process.  Basically an "auto-jump" parameter in the config json to jump to the next class after labeling.  For example, if I label the "left eye", I have to then press the shortcut (which becomes difficult for > 10 landmarks) for the "right eye", and so forth, for the rest of the face.  It should instead just jump to the next label after each click
